# Nome do workflow
name: Generate Snake Animation

# Permissões necessárias
permissions:
  contents: write

# Quando executar
on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa quando fizer push
  push:
    branches:
      - main

# Trabalhos a executar
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Gera a animação da cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Mostra status
      - name: Show status
        run: git status
      
      # Publica na branch output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
